# Generated by Django 5.1.6 on 2025-04-06 23:24

import django.db.models.deletion
import django.utils.timezone
import myloan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone_number', models.CharField(help_text='Lesotho format: +266 followed by 8 digits (e.g. +26650123456)', max_length=15, validators=[myloan.models.validate_lesotho_phone])),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.CharField(blank=True, max_length=200)),
                ('place_of_work', models.CharField(blank=True, max_length=100)),
                ('national_id_number', models.CharField(blank=True, max_length=20)),
                ('id_photo', models.ImageField(blank=True, upload_to='id_photos/')),
                ('credit_score', models.PositiveIntegerField(default=600)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('purpose', models.CharField(choices=[('home_improvement', 'Home Improvement'), ('debt_consolidation', 'Debt Consolidation'), ('business', 'Business Investment'), ('education', 'Education'), ('medical', 'Medical Expenses')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('date_applied', models.DateField(auto_now_add=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('total_payments', models.PositiveIntegerField(default=0)),
                ('payments_made_on_time', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
