# Generated by Django 5.1.6 on 2025-04-07 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='deadline',
            new_name='date_approved',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='total_payments',
            new_name='payments_made',
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('education', 'Education'), ('emergency', 'Emergency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
