
# Generated by Django 5.1.6 on 2025-04-07 00:14
from django.db import migrations, models
from decimal import Decimal

class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0002_rename_deadline_loan_date_approved_and_more'),  # Replace with your last migration
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='deadline',
            field=models.DateField(null=True, blank=True, help_text="Repayment deadline date"),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                default=Decimal('30.00'),
                help_text="Interest rate percentage",
                null=True,
                blank=True
            ),
        ),
    ]