# Generated by Django 5.1.6 on 2025-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0003_add_loan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Interest rate in percentage', max_digits=5),
        ),
    ]
