# Generated by Django 5.1.6 on 2025-04-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0004_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
    ]
