# Generated by Django 5.1.6 on 2025-04-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0005_remove_customuser_occupation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-date_applied'], 'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
    ]
