# Generated by Django 5.2 on 2025-04-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0006_alter_loan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payslip',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
