# Generated by Django 5.2 on 2025-04-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0007_customuser_payslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('amount_lsl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('batch_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('paypal_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_transaction', to='myloan.loan')),
            ],
            options={
                'verbose_name': 'Payout Transaction',
                'verbose_name_plural': 'Payout Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
