# Generated by Django 5.2 on 2025-05-05 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0008_payouttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralBankOfLesotho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('national_id', models.CharField(help_text='Lesotho national identification number', max_length=20, unique=True, verbose_name='National ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Loan Amount (M)')),
                ('date_issued', models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('defaulted', 'Defaulted')], default='active', max_length=10, verbose_name='Loan Status')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Central Bank of Lesotho Debtor',
                'verbose_name_plural': 'Central Bank of Lesotho Debtors',
                'ordering': ['-date_issued'],
                'indexes': [models.Index(fields=['national_id'], name='myloan_cent_nationa_09199a_idx'), models.Index(fields=['status'], name='myloan_cent_status_8df3d2_idx'), models.Index(fields=['last_name', 'first_name'], name='myloan_cent_last_na_cb964d_idx')],
            },
        ),
    ]
