# Generated by Django 5.2.1 on 2025-05-30 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0009_centralbankoflesotho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.CharField(blank=True, help_text='Format: DD/MM/YYYY or YYYY-MM-DD', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PaidAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('amount_lsl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('batch_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('paypal_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_accounts', to='myloan.loan')),
            ],
            options={
                'verbose_name': 'Paid Account',
                'verbose_name_plural': 'Paid Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
