# Generated by Django 5.2.1 on 2025-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloan', '0010_alter_customuser_date_of_birth_paidaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidaccounts',
            name='recipient_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paidaccounts',
            name='status',
            field=models.CharField(default='PAID', max_length=20),
        ),
    ]
